// Generated by CoffeeScript 1.4.0
var Dev, Objective,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Objective = require('../objective');

Dev = (function(_super) {

  __extends(Dev, _super);

  function Dev() {
    return Dev.__super__.constructor.apply(this, arguments);
  }

  return Dev;

})(Objective);
