// Generated by CoffeeScript 1.4.0
var Dev, Objective, dev,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Objective = require('../objective');

Dev = (function(_super) {

  __extends(Dev, _super);

  function Dev() {
    return Dev.__super__.constructor.apply(this, arguments);
  }

  Dev.prototype.protocol = function(When, Then) {
    return When('register:req', function(payload) {
      return Then('register:res', {
        todo: 'send',
        the: 'objective',
        meta: 'data',
        to: 'nimbal'
      });
    });
  };

  return Dev;

})(Objective);

if (typeof dev === 'undefined') {
  dev = new Dev;
}

module.exports = dev;
