// Generated by CoffeeScript 1.4.0
var messenger, start;

start = function(context, notifier, moduleFn) {
  notifier.use(function(msg, next) {
    return next();
  });
  if (context.spec == null) {
    context.spec = './spec';
  }
  if (context.lib == null) {
    context.lib = './lib';
  }
  if (context.src == null) {
    context.src = './src';
  }
  notifier.event('objective::start', {
    "class": 'eo:develop',
    properties: context
  });
  return moduleFn();
};

messenger = function(msg, next) {
  console.log(JSON.stringify(msg.content, null, 2));
  return next();
};

exports.start = start;

exports.messenger = messenger;
