// Generated by CoffeeScript 1.4.0
var eo, messenger;

eo = function(context, notifier, moduleFn) {
  if (context.module == null) {
    context.module = require('./objectives/develop');
  }
  if (typeof context.module === 'string') {
    context.module = require(context.module);
  }
  return context.module.start(context, notifier, moduleFn);
};

messenger = function(msg, next) {
  console.log(JSON.stringify(msg.content, null, 2));
  return next();
};

eo.develop = require('./objectives/develop');

eo.messenger = messenger;

module.exports = eo;
