// Generated by CoffeeScript 1.4.0
var develop, eo, messenger, validate;

develop = require('./objectives/develop');

validate = function(title, opts, objectiveFn) {
  var context, key;
  context = {
    title: title
  };
  for (key in opts) {
    context[key] = opts[key];
  }
  if (typeof title !== 'string') {
    throw new Error('objective(title, opts, fn) requires title as string');
  }
  if (typeof opts.description !== 'string') {
    throw new Error('objective(title, opts, fn) requires opts.description as string');
  }
  if (typeof objectiveFn !== 'function') {
    throw new Error('objective(title, opts, fn) requires function as last argument');
  }
  return context;
};

eo = function(context, notifier, moduleFn) {
  if (context.module == null) {
    context.module = develop;
  }
  if (typeof context.module === 'string') {
    context.module = require(context.module);
  }
  return context.module.start(context, notifier, moduleFn);
};

messenger = function(msg, next) {
  console.log(JSON.stringify(msg.content, null, 2));
  return next();
};

eo.validate = validate;

eo.develop = develop;

eo.messenger = messenger;

module.exports = eo;
