// Generated by CoffeeScript 1.4.0
var plex, uplink;

plex = require('plex');

module.exports = uplink = {
  context: null,
  start: function(uri, secret) {
    console.log('uplinking: ', arguments);
    return uplink.context = plex.start({
      secret: secret,
      connect: {
        adaptor: 'socket.io',
        uri: uri
      }
    });
  }
};
