// Generated by CoffeeScript 1.4.0
var plex, uplink;

plex = require('plex');

module.exports = uplink = {
  context: null,
  start: function(uri, secret, bind) {
    return uplink.context = plex.start({
      secret: secret,
      connect: {
        adaptor: 'socket.io',
        uri: uri
      },
      protocol: bind
    });
  }
};
