// Generated by CoffeeScript 1.4.0
var plex, uplink;

plex = require('plex');

module.exports = uplink = {
  context: null,
  start: function(uri) {
    console.log('uplinking');
    return uplink.context = plex.start({
      connect: {
        adaptor: 'socket.io',
        uri: uri
      }
    });
  }
};
